spring:
  application:
    name: consul-client
  profiles:
    active: dev
  cloud:
    consul:
      discovery:
        enabled: true
        hostname: 47.95.192.77
        port: 8500
        health-check-path: /actuator
        health-check-interval: 10s
        health-check-critical-timeout: 30s

server:
  port: 8080